baseURL: https://switchbackultimate.com/
languageCode: en-us
title: Switchback Ultimate
theme: cleanwhite


params:
  header_image: img/team_picture.jpg

menu:
  main:
    - name: About Us
      url: /aboutus/
      weight: 10
    - name: tryouts
      url: /tryouts2023/
      weight: 15
    - name: scrimmages
      url: /scrimmages/
      weight: 15
    - identifier: Roster
      name: roster
      url: /roster/2023/
      weight: 20
    # - identifier: Schedule
    #   name: schedule
    #   url: /schedule/
    #   weight: 30
    - identifier: Contact
      name: contact
      url: /contact/
      weight: 40
