baseURL: https://switchbackultimate.com/
languageCode: en-us
title: Switchback Ultimate
theme: cleanwhite


params:
  header_image: img/team_picture_blur1.jpg
  custom_css:
    - /css/switchback.css
  social:
    email: "switchbackultimate@gmail.com"
    twitter: "https://twitter.com/switchback_ulti"
    instagram: "https://www.instagram.com/switchback_ulti/"

menu:
  main:
    - name: About Us
      url: /about/
      weight: 10
    - name: tryouts
      url: /tryouts/2025
      weight: 15
    - identifier: Roster
      name: roster
      url: /roster/2025
      weight: 20
    - identifier: Schedule
      name: schedule
      url: /schedule/2025
      weight: 30
    - identifier: Contact
      name: contact
      url: /contact/
      weight: 40
